<?php

declare(strict_types=1);

return [
    'hero' => [
        'label' => 'Hero',
        'table' => 'hero_content',
        'order' => 'id',
        'fields' => [
            'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
            'location_tag' => ['label' => 'Location Tag', 'type' => 'text'],
            'intro' => ['label' => 'Short Intro', 'type' => 'textarea'],
            'primary_cta_label' => ['label' => 'Primary CTA Label', 'type' => 'text'],
            'primary_cta_target' => ['label' => 'Primary CTA Target', 'type' => 'text'],
            'secondary_cta_label' => ['label' => 'Secondary CTA Label', 'type' => 'text'],
            'secondary_cta_target' => ['label' => 'Secondary CTA Target', 'type' => 'text'],
        ],
    ],
    'hero_designations' => [
        'label' => 'Hero Designations',
        'table' => 'hero_designations',
        'order' => 'display_order',
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
            'is_visible' => ['label' => 'Visible', 'type' => 'checkbox'],
        ],
    ],
    'profile_images' => [
        'label' => 'Profile Images',
        'table' => 'profile_images',
        'order' => 'display_order',
        'fields' => [
            'image_path' => ['label' => 'Image', 'type' => 'image', 'required' => true],
            'alt_text' => ['label' => 'Alt Text', 'type' => 'text'],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
            'is_visible' => ['label' => 'Visible', 'type' => 'checkbox'],
        ],
    ],
    'about' => [
        'label' => 'About',
        'table' => 'about_content',
        'order' => 'id',
        'fields' => [
            'summary' => ['label' => 'Professional Summary', 'type' => 'textarea', 'required' => true],
            'stats_json' => ['label' => 'Stats JSON', 'type' => 'textarea', 'hint' => 'Editable JSON array: [{"label":"...", "value":"..."}]'],
        ],
    ],
    'skills' => [
        'label' => 'Skills',
        'table' => 'skills',
        'order' => 'display_order',
        'fields' => [
            'category' => ['label' => 'Category', 'type' => 'text', 'required' => true],
            'name' => ['label' => 'Skill', 'type' => 'text', 'required' => true],
            'proficiency' => ['label' => 'Adjustable Self-Rated Proficiency (%)', 'type' => 'number'],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
            'is_visible' => ['label' => 'Visible', 'type' => 'checkbox'],
        ],
    ],
    'experience' => [
        'label' => 'Experience',
        'table' => 'experience',
        'order' => 'display_order',
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'company' => ['label' => 'Company', 'type' => 'text'],
            'location' => ['label' => 'Location', 'type' => 'text'],
            'period' => ['label' => 'Period', 'type' => 'text'],
            'description' => ['label' => 'Bullet Points', 'type' => 'textarea'],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
        ],
    ],
    'education' => [
        'label' => 'Education',
        'table' => 'education',
        'order' => 'display_order',
        'fields' => [
            'degree' => ['label' => 'Degree', 'type' => 'text', 'required' => true],
            'institution' => ['label' => 'Institution', 'type' => 'text'],
            'location' => ['label' => 'Location', 'type' => 'text'],
            'result' => ['label' => 'Result', 'type' => 'text'],
            'period' => ['label' => 'Period', 'type' => 'text'],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
        ],
    ],
    'projects' => [
        'label' => 'Portfolio Projects',
        'table' => 'projects',
        'order' => 'display_order',
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'role' => ['label' => 'Role', 'type' => 'text'],
            'description' => ['label' => 'Description', 'type' => 'textarea'],
            'features' => ['label' => 'Key Features / Notes', 'type' => 'textarea'],
            'github_url' => ['label' => 'GitHub URL', 'type' => 'url'],
            'live_url' => ['label' => 'Live URL', 'type' => 'url'],
            'featured_image' => ['label' => 'Featured Image', 'type' => 'image'],
            'is_featured' => ['label' => 'Featured', 'type' => 'checkbox'],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
        ],
    ],
    'project_technologies' => [
        'label' => 'Project Technologies',
        'table' => 'project_technologies',
        'order' => 'id',
        'fields' => [
            'project_id' => ['label' => 'Project ID', 'type' => 'number', 'required' => true],
            'technology' => ['label' => 'Technology', 'type' => 'text', 'required' => true],
        ],
    ],
    'tech_stack' => [
        'label' => 'Technology Stack',
        'table' => 'tech_stack',
        'order' => 'display_order',
        'fields' => [
            'name' => ['label' => 'Technology', 'type' => 'text', 'required' => true],
            'logo_path' => ['label' => 'Logo / Icon Image', 'type' => 'image'],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
            'is_visible' => ['label' => 'Visible', 'type' => 'checkbox'],
        ],
    ],
    'certificates' => [
        'label' => 'Certificates',
        'table' => 'certificates',
        'order' => 'display_order',
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'issuer' => ['label' => 'Issuer', 'type' => 'text'],
            'issued_at' => ['label' => 'Issued At', 'type' => 'date'],
            'credential_url' => ['label' => 'Credential URL', 'type' => 'url'],
            'image_path' => ['label' => 'Certificate Image/PDF', 'type' => 'file'],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
        ],
    ],
    'research' => [
        'label' => 'Research',
        'table' => 'research',
        'order' => 'display_order',
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'summary' => ['label' => 'Summary', 'type' => 'textarea'],
            'published_at' => ['label' => 'Published At', 'type' => 'date'],
            'url' => ['label' => 'URL', 'type' => 'url'],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
        ],
    ],
    'testimonials' => [
        'label' => 'Testimonials',
        'table' => 'testimonials',
        'order' => 'display_order',
        'fields' => [
            'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
            'role' => ['label' => 'Role', 'type' => 'text'],
            'message' => ['label' => 'Message', 'type' => 'textarea', 'required' => true],
            'avatar_path' => ['label' => 'Avatar', 'type' => 'image'],
            'is_placeholder' => ['label' => 'Clearly Labeled Placeholder', 'type' => 'checkbox'],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
        ],
    ],
    'faqs' => [
        'label' => 'FAQ',
        'table' => 'faqs',
        'order' => 'display_order',
        'fields' => [
            'question' => ['label' => 'Question', 'type' => 'text', 'required' => true],
            'answer' => ['label' => 'Answer', 'type' => 'textarea', 'required' => true],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
            'is_visible' => ['label' => 'Visible', 'type' => 'checkbox'],
        ],
    ],
    'blog' => [
        'label' => 'Blog',
        'table' => 'blog_posts',
        'order' => 'created_at',
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'slug' => ['label' => 'Slug', 'type' => 'text'],
            'category_id' => ['label' => 'Category', 'type' => 'select', 'options' => []],
            'excerpt' => ['label' => 'Excerpt', 'type' => 'textarea'],
            'content' => ['label' => 'Rich Text Content', 'type' => 'textarea'],
            'featured_image' => ['label' => 'Featured Image', 'type' => 'image'],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['draft' => 'Draft', 'published' => 'Published']],
            'published_at' => ['label' => 'Published At', 'type' => 'datetime-local'],
        ],
    ],
    'blog_categories' => [
        'label' => 'Blog Categories',
        'table' => 'blog_categories',
        'order' => 'display_order',
        'fields' => [
            'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
            'slug' => ['label' => 'Slug', 'type' => 'text', 'required' => true],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
            'is_visible' => ['label' => 'Visible', 'type' => 'checkbox'],
        ],
    ],
    'messages' => [
        'label' => 'Contact Messages',
        'table' => 'contact_messages',
        'order' => 'created_at',
        'readonly_create' => true,
        'fields' => [
            'name' => ['label' => 'Name', 'type' => 'text'],
            'email' => ['label' => 'Email', 'type' => 'email'],
            'subject' => ['label' => 'Subject', 'type' => 'text'],
            'message' => ['label' => 'Message', 'type' => 'textarea'],
            'is_read' => ['label' => 'Read', 'type' => 'checkbox'],
        ],
    ],
    'social_links' => [
        'label' => 'Social Links',
        'table' => 'social_links',
        'order' => 'display_order',
        'fields' => [
            'platform' => ['label' => 'Platform', 'type' => 'text', 'required' => true],
            'label' => ['label' => 'Label', 'type' => 'text'],
            'url' => ['label' => 'URL / Value', 'type' => 'text'],
            'icon' => ['label' => 'Icon Name', 'type' => 'text'],
            'display_order' => ['label' => 'Display Order', 'type' => 'number'],
            'is_visible' => ['label' => 'Visible', 'type' => 'checkbox'],
        ],
    ],
    'seo' => [
        'label' => 'SEO Meta',
        'table' => 'seo_meta',
        'order' => 'id',
        'fields' => [
            'page' => ['label' => 'Page', 'type' => 'text', 'required' => true],
            'title' => ['label' => 'Meta Title', 'type' => 'text'],
            'description' => ['label' => 'Meta Description', 'type' => 'textarea'],
            'og_image' => ['label' => 'OG Image', 'type' => 'image'],
            'twitter_card' => ['label' => 'Twitter Card', 'type' => 'text'],
        ],
    ],
    'settings' => [
        'label' => 'Website Settings',
        'table' => 'settings',
        'order' => 'setting_key',
        'fields' => [
            'setting_key' => ['label' => 'Key', 'type' => 'text', 'required' => true],
            'setting_value' => ['label' => 'Value', 'type' => 'textarea'],
            'setting_type' => ['label' => 'Type', 'type' => 'select', 'options' => ['text' => 'Text', 'image' => 'Image', 'file' => 'File', 'color' => 'Color', 'boolean' => 'Boolean']],
            'group_name' => ['label' => 'Group', 'type' => 'text'],
            'is_public' => ['label' => 'Public', 'type' => 'checkbox'],
        ],
    ],
    'media' => [
        'label' => 'Media Library',
        'table' => 'media_library',
        'order' => 'created_at',
        'fields' => [
            'file_name' => ['label' => 'File Name', 'type' => 'text'],
            'file_path' => ['label' => 'Upload File', 'type' => 'file'],
            'file_type' => ['label' => 'File Type', 'type' => 'text'],
            'alt_text' => ['label' => 'Alt Text', 'type' => 'text'],
        ],
    ],
];
